-------------------------------------------------------------------------------------------------------------------
-- SEED DATA FOR TABLE PARTY_TYPE
-------------------------------------------------------------------------------------------------------------------
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('AUTOMATED_AGENT', NULL, 'Automated Agent');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('CORPORATION', NULL, 'Corporation');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('FAMILY', NULL, 'Family');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('GOVERNMENT_AGENCY', NULL, 'Government Agency');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('INFORMAL_GROUP', NULL, 'Informal Group');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('LEGAL_ORGANIZATION', NULL, 'Legal Organization');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('PARTY_GROUP', NULL, 'Party Group');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('PERSON', NULL, 'Person');
INSERT INTO PARTY_TYPE(PARTY_TYPE_ID, PARENT_TYPE_ID, DESCRIPTION ) VALUES ('TEAM', NULL, 'Team');


